# Generated by Django 6.0.5 on 2026-05-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("especializacion", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_sala", models.CharField(max_length=50)),
                ("capacidad_sala", models.PositiveIntegerField()),
                ("ubicacion_sala", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=50)),
                ("edad_usuario", models.PositiveIntegerField()),
                ("email_usuario", models.EmailField(max_length=100)),
                ("telefono_usuario", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="ResponsableSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_responsable", models.CharField(max_length=50)),
                ("telefono_responsable", models.CharField(max_length=15)),
                ("email_responsable", models.EmailField(max_length=100)),
                (
                    "sala",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsable_sala",
                        to="gestion.sala",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_actividad", models.CharField(max_length=50)),
                ("tipo_actividad", models.CharField(max_length=50)),
                ("horario_actividad", models.CharField(max_length=50)),
                ("descripcion_actividad", models.TextField(max_length=200)),
                ("duracion_actividad", models.PositiveIntegerField()),
                ("plazas_disponibles", models.PositiveIntegerField()),
                (
                    "monitor_actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="gestion.monitor",
                    ),
                ),
                (
                    "sala_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_sala_principal",
                        to="gestion.sala",
                    ),
                ),
                (
                    "salas_secundarias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="actividades_sala_secundaria",
                        to="gestion.sala",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuariosActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_usuario",
                        to="gestion.actividad",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_actividades",
                        to="gestion.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actividad",
            name="usuarios_inscritos_actividad",
            field=models.ManyToManyField(
                blank=True,
                related_name="actividades_inscritas",
                through="gestion.UsuariosActividad",
                to="gestion.usuario",
            ),
        ),
    ]
